export const SUCCESS_CREATE_ROUTE = 'SUCCESS_CREATE_ROUTE';
export const FAILURE_CREATE_ROUTE = 'FAILURE_CREATE_ROUTE';

export const GET_ROUTE_DIRECTIONS = 'GET_ROUTE_DIRECTIONS';

export const TOGGLE_MODAL_STEPS_ON = 'TOGGLE_MODAL_STEPS_ON';
export const TOGGLE_MODAL_STEPS_OFF = 'TOGGLE_MODAL_STEPS_OFF';

export const CLEAR_ROUTING_STEPS = 'CLEAR_ROUTING_STEPS';
