export const SUCCESS_CREATE_POI_SEARCH = 'SUCCESS_CREATE_POI_SEARCH';
export const FAILURE_CREATE_POI_SEARCH = 'FAILURE_CREATE_POI_SEARCH';

export const SELECT_CATEGORY_FILTER = 'SELECT_CATEGORY_FILTER';
export const CLEAR_CATEGORY_FILTER = 'CLEAR_CATEGORY_FILTER';

export const TOGGLE_OPTIONS_TRUE = 'TOGGLE_OPTIONS_TRUE';
export const TOGGLE_OPTIONS_FALSE = 'TOGGLE_OPTIONS_FALSE';
