export const SUCCESS_GET_SEARCH_INFO = "SUCCESS_GET_SEARCH_INFO";
export const FAILURE_GET_SEARCH_INFO = "FAILURE_GET_SEARCH_INFO";

export const INPUT_SEARCH_TEXT = "INPUT_SEARCH_TEXT";
export const CLEAR_INPUT_SEARCH_TEXT = 'CLEAR_INPUT_SEARCH_TEXT';