export const SUCCESS_GET_SEARCH_INFO = "SUCCESS_GET_SEARCH_INFO";
export const FAILURE_GET_SEARCH_INFO = "FAILURE_GET_SEARCH_INFO";

export const INPUT_SEARCH_TEXT = "INPUT_SEARCH_TEXT";

export const SET_LATITUDE = "SET_LATITUDE";
export const SET_LONGITUDE = "SET_LONGITUDE";
