export const INPUT_SEARCH_START_POINT = 'INPUT_SEARCH_START_POINT';
export const INPUT_SEARCH_END_POINT = 'INPUT_SEARCH_END_POINT';

export const START_POINT_VALUE = 'START_POINT_VALUE';
export const END_POINT_VALUE = 'END_POINT_VALUE';

export const SUCCESS_GET_START_POINT = 'SUCCESS_GET_START_POINT';
export const SUCCESS_GET_END_POINT = 'SUCCESS_GET_END_POINT';
export const FAILURE_GET_START_POINT = 'FAILURE_GET_START_POINT';
export const FAILURE_GET_END_POINT = 'FAILURE_GET_END_POINT'